In [20]:
import numpy as np
import math
#block size
J=8
#Number of Bits
N=8

#Sample Data
A=np.array([101,101,100,101,99,101,223,100])


In [27]:
#predictor
S2=np.array([0])
Acap=np.array([])
#unit delay
for i in range(len(A)):
    Acap=np.concatenate([Acap,S2])
    S2=np.array([A[i]])
Acap
    

array([  0., 101., 101., 100., 101.,  99., 101., 223.])

In [28]:
E=np.array([])
E=A-Acap
E    

array([ 101.,    0.,   -1.,    1.,   -2.,    2.,  122., -123.])

In [29]:
#Mapping E to positive integer numbers
xmin=0
xmax=2**N - 1
xmax
for i in range(len(E)):
    theta=min(Acap[i]-xmin,xmax-Acap[i])
    
    if E[i]<=theta and E[i]>=0:
        E[i]=2*E[i]
    elif E[i] <0 and E[i]>=-1*theta:
        E[i]= 2*abs(E[i]) - 1
    else:
        E[i]=theta+ abs(E[i])
E

array([101.,   0.,   1.,   2.,   3.,   4., 223., 155.])

In [31]:
#splitting into J blocks
splitlength=len(E)/J
Jblocks=np.split(E,splitlength)
Jblocks

[array([101.,   0.,   1.,   2.,   3.,   4., 223., 155.])]

TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

In [44]:
def binarr(a,x):
    binnum = [int(i) for i in list('{0:0b}'.format(a))]
    s=np.zeros(x-len(binnum))
    binnum=np.concatenate([s,binnum])
    return binnum

In [52]:
for E in Jblocks:
    #converting each integer in E into binary array
    Ecap=np.array([])
    for i in range(len(E)):
        print(binarr(int(E[i]),N))



[0. 1. 1. 0. 0. 1. 0. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 1.]
[0. 0. 0. 0. 0. 1. 0. 0.]
[1. 1. 0. 1. 1. 1. 1. 1.]
[1. 0. 0. 1. 1. 0. 1. 1.]


In [48]:
Ecap

array([], dtype=float64)